ci:
  autoupdate_schedule: quarterly
  autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v4.0.0-alpha.8'
    hooks:
      - id: prettier
        additional_dependencies:
          - 'prettier@2.5.1'
          - '@carbonplan/prettier@1.2.0'
        language_version: system
        files: "\\.(\
          css|less|scss\
          |graphql|gql\
          |html\
          |js|jsx\
          |ts|tsx\
          |vue\
          |yaml|yml\
          )$"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v4.0.0-alpha.8'
    hooks:
      - id: prettier
        additional_dependencies:
          - 'prettier@2.5.1'
          - '@carbonplan/prettier@1.2.0'
        language_version: system
        name: prettier-markdown
        entry: prettier --write --parser mdx
        files: "\\.(\
          |md|markdown|mdown|mkdn\
          |mdx\
          )$"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: mixed-line-ending
      - id: pretty-format-json
        args: ['--autofix', '--indent=2', '--no-sort-keys']
        exclude: 'ipynb'

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ['--line-length', '100']

  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.9
    hooks:
      - id: blackdoc

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.5.0'
    hooks:
      - id: ruff
        args: ['--fix', '--line-length', '100']

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        args:
          [
            '--extra-keys',
            'metadata.celltoolbar metadata.kernelspec',
            'metadata.language_info.codemirror_mode.version',
            'metadata.language_info.pygments_lexer',
            'metadata.language_info.version',
            'metadata.toc',
            'metadata.notify_time',
            'metadata.varInspector',
            'cell.metadata.heading_collapsed',
            'cell.metadata.hidden',
            'cell.metadata.code_folding',
            'cell.metadata.tags',
            'cell.metadata.init_cell',
          ]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
      - id: nbqa-ruff
        args: ['--fix']
      - id: nbqa-isort
        args: ['--profile=black']
        additional_dependencies: [isort==5.6.4]
      - id: nbqa-black
      - id: nbqa-pyupgrade
        args: ['--py37-plus']
